-- NSF Parallel Topology: Optical Links
-- TP->RDM links use OCH ports on both sides
-- RDM->RDM links use OMS ports on both sides

--- TPcalifornia-RDMcalifornia
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_1', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_2', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_3', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_4', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_5', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_6', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_7', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_8', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_9', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_10', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_11', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_12', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_13', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcalifornia->RDMcalifornia_14', (SELECT id FROM devices WHERE name='TPcalifornia'), (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcalifornia') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPcolorado-RDMcolorado
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_15', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_16', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_17', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_18', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_19', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_20', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_21', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_22', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_23', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_24', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_25', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_26', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_27', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPcolorado->RDMcolorado_28', (SELECT id FROM devices WHERE name='TPcolorado'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPcolorado') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPflorida-RDMflorida
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPflorida->RDMflorida_29', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_30', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_31', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_32', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_33', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_34', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_35', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_36', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_37', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_38', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_39', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_40', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_41', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPflorida->RDMflorida_42', (SELECT id FROM devices WHERE name='TPflorida'), (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPflorida') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPgeorgia-RDMgeorgia
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_43', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_44', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_45', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_46', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_47', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_48', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_49', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_50', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_51', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_52', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_53', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_54', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_55', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPgeorgia->RDMgeorgia_56', (SELECT id FROM devices WHERE name='TPgeorgia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPgeorgia') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPillinois-RDMillinois
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPillinois->RDMillinois_57', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_58', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_59', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_60', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_61', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_62', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_63', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_64', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_65', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_66', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_67', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_68', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_69', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPillinois->RDMillinois_70', (SELECT id FROM devices WHERE name='TPillinois'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPillinois') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPmaryland-RDMmaryland
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_71', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_72', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_73', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_74', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_75', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_76', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_77', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_78', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_79', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_80', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_81', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_82', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_83', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmaryland->RDMmaryland_84', (SELECT id FROM devices WHERE name='TPmaryland'), (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmaryland') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPmichigan-RDMmichigan
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_85', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_86', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_87', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_88', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_89', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_90', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_91', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_92', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_93', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_94', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_95', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_96', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_97', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmichigan->RDMmichigan_98', (SELECT id FROM devices WHERE name='TPmichigan'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmichigan') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPmissouri-RDMmissouri
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_99', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_100', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_101', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_102', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_103', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_104', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_105', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_106', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_107', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_108', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_109', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_110', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_111', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPmissouri->RDMmissouri_112', (SELECT id FROM devices WHERE name='TPmissouri'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPmissouri') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPnewyork-RDMnewyork
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_113', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_114', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_115', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_116', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_117', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_118', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_119', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_120', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_121', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_122', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_123', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_124', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_125', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPnewyork->RDMnewyork_126', (SELECT id FROM devices WHERE name='TPnewyork'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPnewyork') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPpennsylvania-RDMpennsylvania
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_127', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_128', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_129', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_130', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_131', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_132', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_133', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_134', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_135', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_136', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_137', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_138', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_139', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPpennsylvania->RDMpennsylvania_140', (SELECT id FROM devices WHERE name='TPpennsylvania'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPpennsylvania') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPtennessee-RDMtennessee
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_141', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_142', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_143', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_144', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_145', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_146', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_147', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_148', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_149', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_150', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_151', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_152', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_153', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtennessee->RDMtennessee_154', (SELECT id FROM devices WHERE name='TPtennessee'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtennessee') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPtexas-RDMtexas
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPtexas->RDMtexas_155', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_156', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_157', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_158', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_159', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_160', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_161', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_162', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_163', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_164', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_165', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_166', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_167', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPtexas->RDMtexas_168', (SELECT id FROM devices WHERE name='TPtexas'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPtexas') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPvirginia-RDMvirginia
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_169', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_170', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_171', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_172', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_173', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_174', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_175', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_176', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_177', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_178', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_179', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_180', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_181', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPvirginia->RDMvirginia_182', (SELECT id FROM devices WHERE name='TPvirginia'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPvirginia') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TPwashington-RDMwashington
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
	(gen_random_uuid(), 'TPwashington->RDMwashington_183', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1001' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_184', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1002' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_185', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1103' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1003' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_186', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1104' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1004' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_187', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1105' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1005' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_188', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1106' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1006' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_189', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1107' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1007' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_190', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1108' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1008' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_191', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1109' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1009' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_192', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1110' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1010' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_193', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1111' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1011' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_194', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1112' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1012' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_195', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1113' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1013' LIMIT 1), NOW(), NOW()),
	(gen_random_uuid(), 'TPwashington->RDMwashington_196', (SELECT id FROM devices WHERE name='TPwashington'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TPwashington') AND name='1114' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='1014' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMcalifornia-RDMwashington
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMcalifornia->RDMwashington_16', (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='2001' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='2001' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMcalifornia->RDMwashington_44', (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='2004' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMcalifornia-RDMgeorgia
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMcalifornia->RDMgeorgia_17', (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='2001' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMcalifornia->RDMgeorgia_45', (SELECT id FROM devices WHERE name='RDMcalifornia'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcalifornia') AND name='2004' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='2006' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMwashington-RDMtexas
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMwashington->RDMtexas_18', (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='2001' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMwashington->RDMtexas_46', (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='2005' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='2003' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMwashington-RDMnewyork
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMwashington->RDMnewyork_19', (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='2001' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMwashington->RDMnewyork_47', (SELECT id FROM devices WHERE name='RDMwashington'), (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMwashington') AND name='2006' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='2003' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMtexas-RDMgeorgia
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMtexas->RDMgeorgia_20', (SELECT id FROM devices WHERE name='RDMtexas'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtexas') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='2002' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMnewyork-RDMvirginia
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMnewyork->RDMvirginia_21', (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='2001' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMnewyork->RDMvirginia_48', (SELECT id FROM devices WHERE name='RDMnewyork'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMnewyork') AND name='2004' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='2006' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMflorida-RDMgeorgia
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMflorida->RDMgeorgia_22', (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='2001' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='2003' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMflorida-RDMvirginia
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMflorida->RDMvirginia_23', (SELECT id FROM devices WHERE name='RDMflorida'), (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMflorida') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='2002' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMgeorgia-RDMmichigan
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMgeorgia->RDMmichigan_24', (SELECT id FROM devices WHERE name='RDMgeorgia'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMgeorgia') AND name='2004' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='2001' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMvirginia-RDMmichigan
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMvirginia->RDMmichigan_26', (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='2002' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMvirginia-RDMtennessee
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMvirginia->RDMtennessee_28', (SELECT id FROM devices WHERE name='RDMvirginia'), (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMvirginia') AND name='2005' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='2001' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMmichigan-RDMillinois
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMmichigan->RDMillinois_29', (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='2001' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMmichigan->RDMillinois_49', (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='2004' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='2003' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMmichigan->RDMillinois_58', (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='2005' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='2005' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMmichigan->RDMillinois_60', (SELECT id FROM devices WHERE name='RDMmichigan'), (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmichigan') AND name='2006' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='2006' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMillinois-RDMpennsylvania
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMillinois->RDMpennsylvania_30', (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='2001' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMillinois->RDMpennsylvania_50', (SELECT id FROM devices WHERE name='RDMillinois'), (SELECT id FROM devices WHERE name='RDMpennsylvania'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMillinois') AND name='2004' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMpennsylvania') AND name='2004' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMtennessee-RDMmissouri
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMtennessee->RDMmissouri_39', (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='2001' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMtennessee-RDMcolorado
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMtennessee->RDMcolorado_41', (SELECT id FROM devices WHERE name='RDMtennessee'), (SELECT id FROM devices WHERE name='RDMcolorado'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMtennessee') AND name='2005' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMcolorado') AND name='2002' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDMmaryland-RDMmissouri
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, created_at, updated_at) VALUES
(gen_random_uuid(), 'RDMmaryland->RDMmissouri_42', (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='2002' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMmaryland->RDMmissouri_56', (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='2005' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='2004' LIMIT 1), NOW(), NOW()),
(gen_random_uuid(), 'RDMmaryland->RDMmissouri_59', (SELECT id FROM devices WHERE name='RDMmaryland'), (SELECT id FROM devices WHERE name='RDMmissouri'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmaryland') AND name='2006' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDMmissouri') AND name='2006' LIMIT 1), NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

