#!/bin/bash

docker rm -f TPlondon
docker rm -f TPparis
docker rm -f TPfrankfurt
docker rm -f TPamsterdam
docker rm -f TPmadrid
docker rm -f TProme
docker rm -f TPberlin
docker rm -f TPwarsaw
docker rm -f TPstockholm
docker rm -f TPathens
docker rm -f TPcalifornia
docker rm -f TPtexas
docker rm -f TPnewyork
docker rm -f TPflorida
docker rm -f TPillinois
docker rm -f RDMlondon
docker rm -f RDMparis
docker rm -f RDMfrankfurt
docker rm -f RDMamsterdam
docker rm -f RDMmadrid
docker rm -f RDMrome
docker rm -f RDMberlin
docker rm -f RDMwarsaw
docker rm -f RDMstockholm
docker rm -f RDMathens
docker rm -f RDMvienna
docker rm -f RDMprague
docker rm -f RDMbrussels
docker rm -f RDMmilan
docker rm -f RDMzurich
docker rm -f RDMdublin
docker rm -f RDMglasgow
docker rm -f RDMcopenhagen
docker rm -f RDMhamburg
docker rm -f RDMmunich
docker rm -f RDMbudapest
docker rm -f RDMbelgrade
docker rm -f RDMbarcelona
docker rm -f RDMlyon
docker rm -f RDMbordeaux
docker rm -f RDMstrasbourg
docker rm -f RDMoslo
docker rm -f RDMcalifornia
docker rm -f RDMtexas
docker rm -f RDMnewyork
docker rm -f RDMflorida
docker rm -f RDMillinois
docker rm -f RDMpennsylvania
docker rm -f RDMohio
docker rm -f RDMgeorgia
docker rm -f RDMmichigan
docker rm -f RDMwashington
docker rm -f RDMvirginia
docker rm -f RDMarizona
docker rm -f RDMmassachusetts
docker rm -f RDMtennessee
docker rm -f RDMindiana
docker rm -f RDMmissouri
docker rm -f RDMmaryland
docker rm -f RDMcolorado
