-- Pan-EU Topology Devices

INSERT INTO devices (id, name, type, vendor, model, created_at, updated_at) VALUES
(gen_random_uuid(), 'TPlondon', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'TPparis', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'TPfrankfurt', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'TPamsterdam', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'TPmadrid', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'TProme', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'TPberlin', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'TPwarsaw', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'TPstockholm', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'TPathens', 'optical-transponder', 'Cisco', 'NCS1004', NOW(), NOW()),
(gen_random_uuid(), 'RDMlondon', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMparis', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMfrankfurt', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMamsterdam', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMmadrid', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMrome', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMberlin', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMwarsaw', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMstockholm', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMathens', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMvienna', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMprague', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMbrussels', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMmilan', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMzurich', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMdublin', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMglasgow', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMcopenhagen', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMhamburg', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMmunich', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMbudapest', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMbelgrade', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMbarcelona', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMlyon', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMbordeaux', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMstrasbourg', 'optical-roadm', 'Ciena', '6500', NOW(), NOW()),
(gen_random_uuid(), 'RDMoslo', 'optical-roadm', 'Ciena', '6500', NOW(), NOW())
ON CONFLICT (name) DO NOTHING;