-- Topology Reference: ../static/test_topo.pdf
--- TP1-RDM1
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'TP1-RDM1', (SELECT id FROM devices WHERE name='TP1'), (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP1') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='1001' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'TP1-RDM1', (SELECT id FROM devices WHERE name='TP1'), (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP1') AND name='1102' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='1002' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDM1-RDM2
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM1-RDM2', (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='2001' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='1001' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM1-RDM2', (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='1002' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM1-RDM2', (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='1003' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM1-RDM2', (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='2004' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='1004' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDM2-RDM3
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM2-RDM3', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2001' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1001' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM2-RDM3', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1002' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM2-RDM3', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1003' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM2-RDM3', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2004' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1004' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDM2-RDM5
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM2-RDM5', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2005' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='2001' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDM3-RDM4
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM3-RDM4', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='2001' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='2001' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM3-RDM4', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='2002' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM3-RDM4', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='2003' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM3-RDM4', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='2004' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='2004' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDM3-RDM6
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM3-RDM6', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1005' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='1001' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDM4-TP3
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM4-TP3', (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM devices WHERE name='TP3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='1001' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP3') AND name='1101' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM4-TP3', (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM devices WHERE name='TP3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='1002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP3') AND name='1102' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- TP2-RDM5
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'TP2-RDM5', (SELECT id FROM devices WHERE name='TP2'), (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP2') AND name='1101' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='1001' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDM5-RDM6
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM5-RDM6', (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='2002' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='1002' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM5-RDM6', (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='2003' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='1003' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM5-RDM6', (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='2004' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='1004' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;

--- RDM6-TP4
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM6-TP4', (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM devices WHERE name='TP4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='2001' LIMIT 1), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP4') AND name='1101' LIMIT 1), 'FREE', 34359738367, 34359738367, NOW(), NOW())
ON CONFLICT (src_endpoint_id, dst_endpoint_id) DO NOTHING;