-- Topology Reference: ../static/test_topo.pdf
--- TP1-RDM1
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'TP1-RDM1', (SELECT id FROM devices WHERE name='TP1'), (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP1') AND name='1101'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='1001'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'TP1-RDM1', (SELECT id FROM devices WHERE name='TP1'), (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP1') AND name='1102'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='1002'), 'FREE', 34359738367, 34359738367, NOW(), NOW());

--- RDM1-RDM2
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM1-RDM2', (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='2001'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='1001'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM1-RDM2', (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='2002'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='1002'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM1-RDM2', (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='2003'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='1003'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM1-RDM2', (SELECT id FROM devices WHERE name='RDM1'), (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM1') AND name='2004'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='1004'), 'FREE', 34359738367, 34359738367, NOW(), NOW());

--- RDM2-RDM3
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM2-RDM3', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2001'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1001'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM2-RDM3', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2002'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1002'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM2-RDM3', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2003'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1003'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM2-RDM3', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2004'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1004'), 'FREE', 34359738367, 34359738367, NOW(), NOW());

--- RDM2-RDM5
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM2-RDM5', (SELECT id FROM devices WHERE name='RDM2'), (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM2') AND name='2005'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='2001'), 'FREE', 34359738367, 34359738367, NOW(), NOW());

--- RDM3-RDM4
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM3-RDM4', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='2001'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='2001'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM3-RDM4', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='2002'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='2002'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM3-RDM4', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='2003'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='2003'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM3-RDM4', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='2004'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='2004'), 'FREE', 34359738367, 34359738367, NOW(), NOW());

--- RDM3-RDM6
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM3-RDM6', (SELECT id FROM devices WHERE name='RDM3'), (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM3') AND name='1005'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='1001'), 'FREE', 34359738367, 34359738367, NOW(), NOW());

--- RDM4-TP3
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM4-TP3', (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM devices WHERE name='TP3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='1001'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP3') AND name='1101'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM4-TP3', (SELECT id FROM devices WHERE name='RDM4'), (SELECT id FROM devices WHERE name='TP3'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM4') AND name='1002'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP3') AND name='1102'), 'FREE', 34359738367, 34359738367, NOW(), NOW());

--- TP2-RDM5
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'TP2-RDM5', (SELECT id FROM devices WHERE name='TP2'), (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP2') AND name='1101'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='1001'), 'FREE', 34359738367, 34359738367, NOW(), NOW());

--- RDM5-RDM6
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM5-RDM6', (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='2002'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='1002'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM5-RDM6', (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='2003'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='1003'), 'FREE', 34359738367, 34359738367, NOW(), NOW()),
(gen_random_uuid(), 'RDM5-RDM6', (SELECT id FROM devices WHERE name='RDM5'), (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM5') AND name='2004'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='1004'), 'FREE', 34359738367, 34359738367, NOW(), NOW());

--- RDM6-TP4
INSERT INTO optical_links (id, name, src_device_id, dst_device_id, src_endpoint_id, dst_endpoint_id, status, c_slot, l_slot, created_at, updated_at) VALUES (gen_random_uuid(), 'RDM6-TP4', (SELECT id FROM devices WHERE name='RDM6'), (SELECT id FROM devices WHERE name='TP4'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='RDM6') AND name='2001'), (SELECT id FROM endpoints WHERE device_id=(SELECT id FROM devices WHERE name='TP4') AND name='1101'), 'FREE', 34359738367, 34359738367, NOW(), NOW());